{
 "title": "AOSP",
 "description": "Android Open Source Project Data",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "android_permission_group",
    "label": "Grupo de Permisos Android",
    "query": "select permission_group_name from android_permission_group;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboard de AOSP (Android Open Source Project)\n\n---"
   },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  },
  {
   "title": "Grupo de Permisos Android Seleccionado",
   "type": "stat",
   "description": "Representa el grupo/s de permisos Android seleccionado/s en el dashboard.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT DISTINCT\n  android_permission_group_name\nFROM \n  app_warehouse.android_permission \nWHERE \n  android_permission_group_name IN ($android_permission_group) "
    }
   ]
  },
  {
   "title": "Número Total de Grupos de Permisos Seleccionados",
   "type": "stat",
   "description": "Número total de Grupos de Permisos Seleccionados",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  COUNT(DISTINCT android_permission_group_name)\nFROM \n  app_warehouse.android_permission \nWHERE \n  android_permission_group_name IN ($android_permission_group) \n  OR \n  (\"android.permission-group.UNDEFINED\" IN ($android_permission_group) AND android_permission_group_name IS NULL)"
    }
   ]
  },
  {
   "title": "Lista de Permisos Seleccionados",
   "type": "table",
   "description": "Permisos declarados por el sistema operativo Android que pertenecen al grupo/s seleccionado/s.",
   "gridPos": { "h": 15, "w": 9, "x": 6, "y": 11 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  permission_name AS \"Nombre\", added_in_api_level as \"Versión SDK\"\nFROM \n  app_warehouse.android_permission \nWHERE \n  android_permission_group_name IN ($android_permission_group) \n  OR \n  (\"android.permission-group.UNDEFINED\" IN ($android_permission_group) AND android_permission_group_name IS NULL)"
    }
   ]
  },
  {
   "title": "Distribución de la versión de SDK de los Permisos seleccionados",
   "type": "barchart",
   "description": "Representa la distribución de la versión de SDK del sistema Android en que se incluyeron los permisos seleccionados. No se tienen en cuenta los permisos de los que no se tiene esta información.",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  added_in_api_level AS \"SDK\", COUNT(*) AS \"Nº de Permisos\"\nFROM \n  app_warehouse.android_permission \nWHERE \n  (android_permission_group_name IN ($android_permission_group) \n  OR \n  (\"android.permission-group.UNDEFINED\" IN ($android_permission_group) AND android_permission_group_name IS NULL))\n  AND\n  added_in_api_level IS NOT NULL\n  AND\n  added_in_api_level != \"UpsideDownCake\"\nGROUP BY\n  added_in_api_level\nORDER BY \n  CAST(added_in_api_level AS UNSIGNED)"
    }
   ]
  },
  {
   "title": "Número Total de Permisos Seleccionados",
   "type": "stat",
   "description": "Número total de Permisos Seleccionados",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  COUNT(permission_name)\nFROM \n  app_warehouse.android_permission \nWHERE \n  android_permission_group_name IN ($android_permission_group) \n  OR \n  (\"android.permission-group.UNDEFINED\" IN ($android_permission_group) AND android_permission_group_name IS NULL)"
    }
   ]
  },
  {
   "title": "Menu",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 26 },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  }
 ]
}