{
 "title": "App",
 "description": "Panel de mandos de Aplicaciones Android",
 "time": { "from": "2024-08-13T06:12:01.004Z", "to": "2024-08-17T06:12:01.020Z" },
 "templating": {
  "list": [
   {
    "name": "package",
    "label": "Nombre de paquete",
    "query": "SELECT package FROM app WHERE hash IN (SELECT app_hash FROM az_metadata WHERE rating_count > 1);"
   },
   {
    "name": "version_name",
    "label": "Versión",
    "query": "SELECT version_name FROM app WHERE package='$package';"
   },
   {
    "name": "hash",
    "label": "Hash",
    "query": "SELECT hash FROM app WHERE package='$package' AND version_name='$version_name'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "# Dashboard de Apps\n\n---" },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  },
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Nombre",
   "type": "stat",
   "description": "Nombre de la aplicación seleccionada.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT app_title FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Categoría",
   "type": "stat",
   "description": "Categoría de la aplicación seleccionada",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT category FROM app_warehouse.app WHERE hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nombre de Paquete",
   "type": "stat",
   "description": "Nombre de paquete que identifica la aplicación seleccionada.",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT package FROM app_warehouse.app WHERE hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Min SDK",
   "type": "stat",
   "description": "Versión mínima de SDK de Android requerida para el funcionamiento de la aplicación.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT min_sdk_version FROM app_warehouse.app WHERE hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Fecha de publicación",
   "type": "stat",
   "description": "Fecha de salida de la aplicación en Google Play.",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT uplaod_date FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Versión",
   "type": "stat",
   "description": "Versión de la aplicación seleccionada.",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT version_name FROM app_warehouse.app WHERE hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Tamaño en MB",
   "type": "stat",
   "description": "Tamaño de la aplicación seleccionada en MB.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A*2**(-20)", "type": "math" }
   ]
  },
  { "title": "Popularidad y Valoraciones", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Puntuación media",
   "type": "gauge",
   "description": "Puntuación media de la app sobre 5.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT star_rating FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Distribución de la Puntuación",
   "type": "barchart",
   "description": "Distribución de las valoraciones de la aplicación.",
   "gridPos": { "h": 8, "w": 11, "x": 4, "y": 10 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \"Estrellas\", AVG(one_star_ratings) AS \"1\", AVG(two_star_ratings) AS \"2\", AVG(three_star_ratings) AS \"3\", AVG(four_star_ratings) AS \"4\", AVG(five_star_ratings) AS \"5\" FROM app_warehouse.az_metadata WHERE app_hash = '$hash' GROUP BY app_hash LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nº de Descargas",
   "type": "stat",
   "description": "Número total de descargas de la app.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT num_downloads FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Nº de Valoraciones",
   "type": "stat",
   "description": "Número total de valoraciones.",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT rating_count FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  { "title": "Desarrollador", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Desarrollador",
   "type": "stat",
   "description": "Desarrollador de la aplicación.",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT developer_name FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Dirección del Desarrollador",
   "type": "stat",
   "description": "Dirección del desarrollador de la aplicación.",
   "gridPos": { "h": 3, "w": 17, "x": 7, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT developer_address FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Email del Desarrollador",
   "type": "stat",
   "description": "Email del desarrollador de la aplicación.",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT developer_email FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Web del Desarrollador",
   "type": "stat",
   "description": "Página web del desarrollador de la aplicación.",
   "gridPos": { "h": 3, "w": 17, "x": 7, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT developer_website FROM app_warehouse.az_metadata WHERE app_hash = '$hash' LIMIT 50 "
    }
   ]
  },
  { "title": "Menu", "gridPos": { "h": 3, "w": 6, "x": 9, "y": 25 } }
 ]
}