{
 "title": "Comparación de Apps en Privacidad",
 "description": "Permite comparar aplicaciones concretas entre si en términos de privacidad.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "privacy_rank_name",
    "label": "Métrica de Privacidad",
    "query": "SELECT privacy_rank_name FROM privacy_rank WHERE privacy_rank_name = \"RPNDroid\""
   },
   {
    "name": "packageA",
    "label": "Nombre de paquete de la app A",
    "query": "SELECT package FROM app WHERE hash IN (SELECT app_hash FROM az_metadata WHERE rating_count > 1);"
   },
   {
    "name": "version_nameA",
    "label": "Versión de la App A",
    "query": "SELECT version_name FROM app WHERE package='$packageA';"
   },
   {
    "name": "hashA",
    "label": "Hash de la App A",
    "query": "SELECT hash FROM app WHERE package='$packageA' AND version_name='$version_nameA'"
   },
   {
    "name": "categoryA",
    "label": "Categoría de la App A",
    "query": "SELECT category FROM app WHERE package='$packageA' AND version_name='$version_nameA'"
   },
   {
    "name": "packageB",
    "label": "Nombre de paquete de la app B",
    "query": "SELECT package FROM app WHERE hash IN (SELECT app_hash FROM az_metadata WHERE rating_count > 1);"
   },
   {
    "name": "version_nameB",
    "label": "Versión de la App B",
    "query": "SELECT version_name FROM app WHERE package='$packageB';"
   },
   {
    "name": "hashB",
    "label": "Hash de la App B",
    "query": "SELECT hash FROM app WHERE package='$packageB' AND version_name='$version_nameB'"
   },
   {
    "name": "categoryB",
    "label": "Categoría de la App B",
    "query": "SELECT category FROM app WHERE package='$packageB' AND version_name='$version_nameB'"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboard de Comparaciones de Apps en Privacidad\n\n---"
   },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  },
  {
   "title": "Nombre de la App A",
   "type": "stat",
   "description": "Nombre de la aplicación A seleccionada.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  app_title \nFROM \n  app_warehouse.az_metadata\nWHERE \n  app_hash IN (SELECT hash FROM app WHERE package='$packageA')"
    }
   ]
  },
  {
   "title": "Permisos Solicitados",
   "type": "stat",
   "description": "Número de permisos que solicita la App $packageA",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  COUNT(permission_name) \nFROM \n  app_warehouse.app_uses_permission\nWHERE \n  app_hash='$hashA'"
    }
   ]
  },
  {
   "title": "Permisos Custom Solicitados",
   "type": "stat",
   "description": "Número de permisos custom que solicita la App $packageA",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  COUNT(permission_name) \nFROM \n  app_warehouse.app_uses_permission\nWHERE \n  app_hash='$hashA'\n  AND \n  permission_name NOT IN (SELECT permission_name FROM app_warehouse.android_permission)"
    }
   ]
  },
  {
   "title": "Nombre de la App B",
   "type": "stat",
   "description": "Nombre de la aplicación B seleccionada.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  app_title \nFROM \n  app_warehouse.az_metadata\nWHERE \n  app_hash IN (SELECT hash FROM app WHERE package='$packageB')"
    }
   ]
  },
  {
   "title": "Permisos Solicitados",
   "type": "stat",
   "description": "Número de permisos que solicita la App $packageB",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  COUNT(permission_name) \nFROM \n  app_warehouse.app_uses_permission\nWHERE \n  app_hash='$hashB'"
    }
   ]
  },
  {
   "title": "Permisos Custom Solicitados",
   "type": "stat",
   "description": "Número de permisos custom que solicita la App $packageB",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  COUNT(permission_name) \nFROM \n  app_warehouse.app_uses_permission\nWHERE \n  app_hash='$hashB'\n  AND \n  permission_name NOT IN (SELECT permission_name FROM app_warehouse.android_permission)"
    }
   ]
  },
  {
   "title": "Puntuación obtenida para $packageA por $privacy_rank_name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  score_value \nFROM \n  app_warehouse.score\nWHERE \n  app_hash='$hashA'\n  AND \n  privacy_rank_name='$privacy_rank_name' "
    }
   ]
  },
  {
   "title": "Peso que aporta cada grupo de permisos a la métrica",
   "type": "bargauge",
   "description": "Peso que aporta cada grupo de permisos solicitado por la app $packageA a la Métrica",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 7 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  SUM(r.rank_value), a.android_permission_group_name \nFROM \n  permission_rank AS r JOIN android_permission AS a\nON \n  r.permission_name=a.permission_name\nWHERE \n  r.permission_name IN (\n    SELECT\n      permission_name\n    FROM\n      app_uses_permission\n    WHERE\n      app_hash='$hashA'\n  )\n  AND\n  a.android_permission_group_name IS NOT NULL\nGROUP BY\n  a.android_permission_group_name\nORDER BY\n  SUM(r.rank_value) DESC"
    }
   ]
  },
  {
   "title": "Puntuación obtenida para $packageB por $privacy_rank_name",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  score_value \nFROM \n  app_warehouse.score\nWHERE \n  app_hash='$hashB'\n  AND \n  privacy_rank_name='$privacy_rank_name' "
    }
   ]
  },
  {
   "title": "Peso que aporta cada grupo de permisos a la métrica",
   "type": "bargauge",
   "description": "Peso que aporta cada grupo de permisos solicitado por la app $packageB a la Métrica",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  SUM(r.rank_value), a.android_permission_group_name \nFROM \n  permission_rank AS r JOIN android_permission AS a\nON \n  r.permission_name=a.permission_name\nWHERE \n  r.permission_name IN (\n    SELECT\n      permission_name\n    FROM\n      app_uses_permission\n    WHERE\n      app_hash='$hashB'\n  )\n  AND\n  a.android_permission_group_name IS NOT NULL\nGROUP BY\n  a.android_permission_group_name\nORDER BY\n  SUM(r.rank_value) DESC"
    }
   ]
  },
  {
   "title": "Evolución de la Métrica $privacy_rank_name para $packageA",
   "type": "trend",
   "description": "Evolución del valor de la Métrica $privacy_rank_name para la app $packageA en función de las versiones de la misma.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  a.version_code AS \"Código de Versión\", s.score_value AS \"Valor de la Métrica\" \nFROM \n  app_warehouse.score AS s JOIN app AS a\nON\n  s.app_hash=a.hash\nWHERE \n  a.package='$packageA'\n  AND\n  s.privacy_rank_name='$privacy_rank_name'\nORDER BY\n a.version_code"
    }
   ]
  },
  {
   "title": "Otras sugerencias en $categoryA",
   "type": "table",
   "description": "Aplicaciones sugeridas según el valor de la métrica.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  a.package AS \"Nombre de Paquete\", a.version_name AS \"Versión\", s.score_value AS \"Métrica\"\nFROM\n  app AS a JOIN score AS s\nON\n  a.hash=s.app_hash\nWHERE\n  a.category='$categoryA'\n  AND\n  s.privacy_rank_name='$privacy_rank_name'\n  AND\n  s.score_value < (SELECT score_value FROM app_warehouse.score WHERE app_hash='$hashA' AND privacy_rank_name='$privacy_rank_name')\nORDER BY s.score_value DESC"
    }
   ]
  },
  {
   "title": "Evolución de la Métrica $privacy_rank_name para $packageB",
   "type": "trend",
   "description": "Evolución del valor de la Métrica $privacy_rank_name para la app $packageB en función de las versiones de la misma.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  a.version_code AS \"Código de Versión\", s.score_value AS \"Valor de la Métrica\" \nFROM \n  app_warehouse.score AS s JOIN app AS a\nON\n  s.app_hash=a.hash\nWHERE \n  a.package='$packageB'\n  AND\n  s.privacy_rank_name='$privacy_rank_name'\nORDER BY\n a.version_code"
    }
   ]
  },
  {
   "title": "Otras sugerencias en $categoryB",
   "type": "table",
   "description": "Aplicaciones sugeridas según el valor de la métrica.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  a.package AS \"Nombre de Paquete\", a.version_name AS \"Versión\", s.score_value AS \"Métrica\"\nFROM\n  app AS a JOIN score AS s\nON\n  a.hash=s.app_hash\nWHERE\n  a.category='$categoryB'\n  AND\n  s.privacy_rank_name='$privacy_rank_name'\n  AND\n  s.score_value < (SELECT score_value FROM app_warehouse.score WHERE app_hash='$hashB' AND privacy_rank_name='$privacy_rank_name')\nORDER BY s.score_value DESC"
    }
   ]
  },
  {
   "title": "Politica de Privacidad de $packageA",
   "type": "stat",
   "description": "Política de privacidad de $packageA",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT privacy_policy_url FROM app_warehouse.az_metadata WHERE app_hash = '$hashA' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Politica de Privacidad de $packageB",
   "type": "stat",
   "description": "Política de privacidad de $packageB",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT privacy_policy_url FROM app_warehouse.az_metadata WHERE app_hash = '$hashB' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Menu",
   "type": "dashlist",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 26 },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  }
 ]
}