{
 "title": "Menu",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "# Dashboard de App-PIMD\n\n---" },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  },
  {
   "title": "Número de Aplicaciones en el Repositorio",
   "type": "stat",
   "description": "Número total de aplicaciones almacenadas en el repositorio.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT COUNT(hash) FROM app_warehouse.app LIMIT 50 "
    }
   ]
  },
  {
   "title": "Número de Fuentes de Datos de Aplicaciones",
   "type": "stat",
   "description": "Número total de fuentes origen utilizadas para nutrir el repositorio.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT COUNT(DISTINCT extraction_source) FROM app_warehouse.extraction_metadata LIMIT 50 "
    }
   ]
  },
  {
   "title": "Número total de permisos almacenados",
   "type": "stat",
   "description": "Número total de permisos definidos por el sistema operativo Android o Custom almacenados en el repositorio.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT COUNT(permission_name) FROM app_warehouse.permission LIMIT 50 "
    }
   ]
  },
  {
   "title": "Menu Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  }
 ]
}