{
 "title": "Análisis de Privacidad",
 "description": "Panel de mandos para analizar el estado en la privacidad general de aplicaciones Android. ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "privacy_rank_name",
    "label": "Métrica de Privacidad",
    "query": "SELECT privacy_rank_name FROM privacy_rank"
   },
   {
    "name": "category",
    "label": "Categoría",
    "query": "SELECT DISTINCT category FROM app"
   },
   {
    "name": "min_sdk_version",
    "label": "Versión mínima de SDK",
    "query": "SELECT DISTINCT min_sdk_version FROM app ORDER BY min_sdk_version"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Dashboard de Análisis de Privacidad en Aplicaciones Android\n\n---"
   },
   "targets": [
    { "dataset": "app_warehouse" }
   ]
  },
  { "title": "Por Categoría", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Categoría Seleccionada",
   "type": "stat",
   "description": "Categoría de aplicaciones Android.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT category FROM app_warehouse.app WHERE category = '$category' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Valoración $privacy_rank_name promedio",
   "type": "gauge",
   "description": "Valor promedio de la métrica de privacidad $privacy_rank_name en la categoría $category",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  AVG(score_value) \nFROM\n  score\nWHERE\n  app_hash IN (SELECT hash FROM app WHERE category='$category')\n  AND\n  privacy_rank_name='$privacy_rank_name' "
    }
   ]
  },
  {
   "title": "Distribución de las puntuaciones de $privacy_rank_name en $category",
   "type": "histogram",
   "description": "Distribución de las puntuaciones obtenidas",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 3 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  score_value \nFROM\n  score\nWHERE\n  app_hash IN (SELECT hash FROM app WHERE category='$category')\n  AND\n  privacy_rank_name='$privacy_rank_name' "
    }
   ]
  },
  {
   "title": "Puntuación promedio por Métrica para la categoría $category",
   "type": "barchart",
   "description": "Muestra la puntuación promedio que obtienen las apps de la categoría $category para cada métrica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  AVG(score_value), privacy_rank_name\nFROM\n  score\nWHERE\n  app_hash IN (SELECT hash FROM app WHERE category='$category')\nGROUP BY \n  privacy_rank_name"
    }
   ]
  },
  {
   "title": "Número de Aplicaciones en $category",
   "type": "stat",
   "description": "Número de aplicaciones involucradas en la selección.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT COUNT(hash) FROM app_warehouse.app WHERE category = '$category' LIMIT 50 "
    }
   ]
  },
  { "title": "Por SDK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Versión mínima de SDK Seleccionada",
   "type": "stat",
   "description": "Versión mínima de SDK Seleccionada.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT DISTINCT min_sdk_version FROM app_warehouse.app WHERE min_sdk_version=$min_sdk_version "
    }
   ]
  },
  {
   "title": "Valoración $privacy_rank_name promedio",
   "type": "gauge",
   "description": "Valor promedio de la métrica de privacidad $privacy_rank_name con el SDK mínimo seleccionado $min_sdk_version",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  AVG(score_value) \nFROM\n  score\nWHERE\n  app_hash IN (SELECT hash FROM app WHERE min_sdk_version=$min_sdk_version)\n  AND\n  privacy_rank_name='$privacy_rank_name' "
    }
   ]
  },
  {
   "title": "Distribución de las puntuaciones de $privacy_rank_name con SDK $min_sdk_version",
   "type": "histogram",
   "description": "Distribución de las puntuaciones obtenidas",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 12 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  score_value \nFROM\n  score\nWHERE\n  app_hash IN (SELECT hash FROM app WHERE min_sdk_version=$min_sdk_version)\n  AND\n  privacy_rank_name='$privacy_rank_name' "
    }
   ]
  },
  {
   "title": "Puntuación promedio por Métrica para el SDK $min_sdk_version",
   "type": "barchart",
   "description": "Muestra la puntuación promedio que obtienen las apps con versión mínima de SDK $min_sdk_version para cada métrica.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  AVG(score_value), privacy_rank_name\nFROM\n  score\nWHERE\n  app_hash IN (SELECT hash FROM app WHERE min_sdk_version=$min_sdk_version)\nGROUP BY \n  privacy_rank_name"
    }
   ]
  },
  {
   "title": "Número de Aplicaciones con SDK $min_sdk_version",
   "type": "stat",
   "description": "Número de aplicaciones involucradas en la selección.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT COUNT(hash) FROM app_warehouse.app WHERE min_sdk_version=$min_sdk_version "
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Intrusividad $privacy_rank_name por Dependencia",
   "type": "barchart",
   "description": "Representa la valoración promedio $privacy_rank_name según dependencia de aplicación.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  a.az_dependency_package AS \"Dependencia\", AVG(s.score_value) AS \"Valor de la Métrica\"\nFROM \n  score AS s JOIN az_bind_dependency AS a ON s.app_hash=a.az_metadata_app_hash \nWHERE \n  s.score_value IS NOT NULL \n  AND \n  s.privacy_rank_name='$privacy_rank_name'\nGROUP BY\n  a.az_dependency_package\nORDER BY \n  AVG(s.score_value)"
    }
   ]
  },
  {
   "title": "Métrica $privacy_rank_name según Valoración",
   "type": "trend",
   "description": "Muestra la progresión del promedio de la métrica $privacy_rank_name según el número de estrellas de valoración.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  a.star_rating AS \"Valoración\", AVG(s.score_value) AS \"Valor Promedio de la Métrica\"\nFROM \n  score AS s JOIN az_metadata AS a ON s.app_hash=a.app_hash \nWHERE \n  s.score_value IS NOT NULL \n  AND \n  s.privacy_rank_name='$privacy_rank_name'\nGROUP BY \n  a.star_rating\nORDER BY \n  a.star_rating"
    }
   ]
  },
  {
   "title": "Valor de la Métrica $privacy_rank_name vs. Tamaño en MB de la app",
   "type": "xychart",
   "description": "Muestra la relación entre la intrusividad en la privacidad de las aplicaciones y su tamaño.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "dataset": "app_warehouse",
     "rawSql": "SELECT \n  a.size * POW(2, -20) AS \"Tamaño (MB)\", s.score_value AS \"Valor de la Métrica\", app_title AS \"Nombre\"\nFROM \n  score AS s JOIN az_metadata AS a ON s.app_hash=a.app_hash \nWHERE \n  s.score_value IS NOT NULL \n  AND \n  s.privacy_rank_name='$privacy_rank_name';"
    }
   ]
  },
  { "title": "Menu", "gridPos": { "h": 3, "w": 6, "x": 9, "y": 29 } }
 ]
}